---
name: Automated CICD pipline 
on:
  push:
    branches: [ main ]
jobs:
  build-and-push:
    name: Build_and_Push_to_Dockerhub
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Login to Dockerhub
      env:
        DOCKER_USER: ${{secrets.DOCKER_USER}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD

    - name: Automatic Tagging of Releases
      id: increment-git-tag
      run: |
        bash ./build/git_update.sh -v minor 

    - name: Build, Tag, and Push the Image to Dockerhub
      id: build-image
      env:
        IMAGE_TAG: ${{ steps.increment-git-tag.outputs.git-tag }}
      run: |
        docker build --file Dockerfile --tag hachemguetif/cicd:$IMAGE_TAG .
        docker push hachemguetif/cicd:$IMAGE_TAG



  Deploy:
    name: Update Image tag in ArgoCD repository
    needs: [Build_and_Push_to_Dockerhub]
    runs-on: ubuntu-latest
    steps:
    - name: Update Image tags in ArgoCD repo.
      run: |
          
          git clone https://github.com/hachemguetif/ArgoCD-repo /tmp/Webapp-ArgoCD
          cd /tmp/Webapp-ArgoCD
          sed -i 's/\(cicd\)\(.*\)/\1:'$IMAGE_TAG'/' ./deployments/deployment.yaml
          git config --global credential.helper 'cache --timeout 3600'
          git config user.email "hachem.guetiff@gmail.com"
          git config user.name "hachemguetif"
          git add .
          git commit -m "new image tag update"
          git remote set-url origin "https://hachemguetif:${token}@github.com/hachemguetif/ArgoCD-repo.git"
          git push origin main

      env: 
        token: ${{ secrets.PERSONAL_GITHUB_TOKEN }}
        
 
          
