---
name: Build and Push Golang Image to Dockerhub
on:
  push:
    branches: [ main ]
jobs:
  build-and-push:
    name: Build and Push to Dockerhub
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Login to Dockerhub
      env:
        DOCKER_USER: ${{secrets.DOCKER_USER}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD

    - name: Automatic Tagging of Releases
      id: increment-git-tag
      run: |
        bash ./build/git_update.sh -v patch 

    - name: Build, Tag, and Push the Image to Dockerhub
      id: build-image
      env:
        IMAGE_TAG: ${{ steps.increment-git-tag.outputs.git-tag }}
      run: |
        docker build --file Dockerfile --tag hachemguetif/cicd:$IMAGE_TAG .
        docker push hachemguetif/cicd:$IMAGE_TAG

  Update-ArgoCD-repo:
    name: Update Image tags in ArgoCD repo
    runs-on: ubuntu-latest
    steps:
    - name: update
      run: |
          git clone https://github.com/hachemguetif/ArgoCD-repo /tmp/Webapp-ArgoCD
          cd /tmp/Webapp-ArgoCD
          sed -i 's/\(cicd\)\(.*\)/\1:'$IMAGE_TAG'/' ./deployment.yaml
          git config --global credential.helper 'cache --timeout 3600'
          
          git config user.email "hachem.guetiff@gmail.com"
          git config user.name "hachemguetif"
          git add .
          git commit -m "new tag image update"
          # Push quietly to prevent showing the token in log
          git push -q https://$PERSONAL_GITHUB_TOKEN@github.com/hachemguetif/ArgoCD-repo.git main
 
          
